CREATE TABLE users (
 id UUID NOT NULL PRIMARY KEY,
 name VARCHAR(50) NOT NULL,
 email VARCHAR(50) NOT NULL,
 password VARCHAR(50) NOT NULL,
 gender VARCHAR(6) NOT NULL,
 account_type VARCHAR(6) DEFAULT 'normal',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)